name: Send Site to Pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Run project build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-.

      - name: Build application
        run: ./gradlew build --full-stacktrace

      - name: Check report files
        run: |
          ls build/distributions

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-build-report
          path: build/distributions

  saveFiles:
    name: SaveReport
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          repository: stslex/stslex.github.io
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Create local changes
        run: |
          rm -rf docs
          mkdir docs

      - name: Download report
        uses: actions/download-artifact@v3
        with:
          name: code-build-report
          path: docs

      - name: Check report files
        run: |
          ls docs

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -m "Add changes" -a

      - name: Push changd
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          repository: stslex/stslex.github.io
          branch: main